name: main
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '* * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: sudo pip install requests
      - run: sudo pip install opencv-python
      - run: sudo pip install selenium
      - run: sudo python ./test.py
      
